//! Contains structures and functions related to transaction creation.

use alloc::boxed::Box;
use alloc::collections::{BTreeMap, BTreeSet};
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::num::NonZeroU16;

use miden_protocol::account::{AccountCodeInterface, AccountId};
use miden_protocol::asset::Asset;
use miden_protocol::crypto::merkle::MerkleError;
use miden_protocol::crypto::merkle::store::MerkleStore;
use miden_protocol::errors::{
    AccountError,
    AssetError,
    AssetVaultError,
    NoteError,
    StorageMapError,
    TransactionInputError,
};
use miden_protocol::note::{
    Note,
    NoteDetails,
    NoteDetailsCommitment,
    NoteId,
    NoteRecipient,
    NoteScript,
    NoteTag,
    PartialNote,
};
use miden_protocol::transaction::{
    InputNote,
    InputNotes,
    TransactionArgs,
    TransactionId,
    TransactionScript,
};
use miden_protocol::vm::AdviceMap;
use miden_protocol::{MastForestScriptError, Word};
use miden_standards::account::auth::{FeeConversionInfo, commit_fee_conversion_info};
use miden_standards::errors::CodeBuilderError;
use miden_standards::tx_script::{
    ExpirationTransactionScript,
    SendNotesTransactionScript,
    SendNotesTransactionScriptError,
};
use miden_tx::utils::serde::{
    ByteReader,
    ByteWriter,
    Deserializable,
    DeserializationError,
    Serializable,
};
use thiserror::Error;

mod builder;
pub use builder::{
    PaymentNoteDescription,
    PswapTransactionData,
    SwapTransactionData,
    TransactionRequestBuilder,
};

mod foreign;
pub(crate) use foreign::account_proof_into_inputs;
pub use foreign::{ForeignAccount, build_fpi_script};

use crate::store::InputNoteRecord;

// TRANSACTION REQUEST
// ================================================================================================

pub type NoteArgs = Word;

/// Specifies a transaction script to be executed in a transaction.
///
/// A transaction script is a program which is executed after scripts of all input notes have been
/// executed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TransactionScriptTemplate {
    /// Specifies the exact transaction script to be executed in a transaction.
    CustomScript(TransactionScript),
    /// Specifies that the transaction script must create the specified output notes.
    ///
    /// It is up to the client to determine how the output notes will be created and this will
    /// depend on the capabilities of the account the transaction request will be applied to. For
    /// example, for Basic Wallets, this may involve invoking `create_note` procedure.
    SendNotes(Vec<PartialNote>),
}

/// Specifies a transaction request that can be executed by an account.
///
/// A request contains information about input notes to be consumed by the transaction (if any),
/// description of the transaction script to be executed (if any), and a set of notes expected to be
/// generated by the transaction or by consuming notes generated by the transaction.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TransactionRequest {
    /// Notes to be consumed by the transaction, in consumption order.
    ///
    /// A note with an entry in `explicit_input_notes` is consumed in the mode that entry pins. The
    /// executing client infers the mode of every other note from its store.
    input_notes: Vec<Note>,
    /// Optional arguments of the input notes to be consumed by the transaction. This includes both
    /// authenticated and unauthenticated notes.
    input_notes_args: Vec<(NoteId, Option<NoteArgs>)>,
    /// Pinned consumption modes set through [`TransactionRequestBuilder::explicit_input_notes`].
    pub(super) explicit_input_notes: BTreeMap<NoteId, InputNote>,
    /// Template for the creation of the transaction script.
    script_template: Option<TransactionScriptTemplate>,
    /// A map of recipients of the output notes expected to be generated by the transaction.
    expected_output_recipients: BTreeMap<Word, NoteRecipient>,
    /// A map of details and tags of notes we expect to be created as part of future transactions
    /// with their respective tags.
    ///
    /// For example, after a swap note is consumed, a payback note is expected to be created.
    expected_future_notes: BTreeMap<NoteDetailsCommitment, (NoteDetails, NoteTag)>,
    /// Initial state of the `AdviceMap` that provides data during runtime.
    advice_map: AdviceMap,
    /// Initial state of the `MerkleStore` that provides data during runtime.
    merkle_store: MerkleStore,
    /// Foreign account data requirements keyed by account ID. At execution time, account data will
    /// be retrieved from the network, and injected as advice inputs. Additionally, the account's
    /// code will be added to the executor and prover.
    foreign_accounts: BTreeMap<AccountId, ForeignAccount>,
    /// The number of blocks in relation to the transaction's reference block after which the
    /// transaction will expire. If `None`, the transaction will not expire.
    expiration_delta: Option<u16>,
    /// Indicates whether to **silently** ignore invalid input notes when executing the transaction.
    /// This will allow the transaction to be executed even if some input notes are invalid.
    ignore_invalid_input_notes: bool,
    /// Optional [`Word`] that will be pushed to the operand stack before the transaction script
    /// execution.
    script_arg: Option<Word>,
    /// Optional [`Word`] that will be pushed to the stack for the authentication procedure during
    /// transaction execution.
    auth_arg: Option<Word>,
    /// Salt the native fee conversion info is committed under when the transaction is prepared, set
    /// through [`TransactionRequestBuilder::fee_conversion_salt`]. `None` leaves the client to use
    /// its fixed default salt.
    fee_conversion_salt: Option<Word>,
    /// Note scripts that the node's NTX builder will need in its script registry.
    ///
    /// See [`TransactionRequestBuilder::expected_ntx_scripts`] for details.
    expected_ntx_scripts: Vec<NoteScript>,
}

impl TransactionRequest {
    // PUBLIC ACCESSORS
    // --------------------------------------------------------------------------------------------

    /// Returns a reference to the transaction request's input note list.
    pub fn input_notes(&self) -> &[Note] {
        &self.input_notes
    }

    /// Returns a list of all input note IDs.
    pub fn input_note_ids(&self) -> impl Iterator<Item = NoteId> {
        self.input_notes.iter().map(Note::id)
    }

    /// Returns the assets held by the transaction's input notes.
    pub fn incoming_assets(&self) -> (BTreeMap<AccountId, u64>, Vec<Asset>) {
        collect_assets(self.input_notes.iter().flat_map(|note| note.assets().iter()))
    }

    /// Returns a map of note IDs to their respective [`NoteArgs`]. The result will include
    /// exclusively note IDs for notes for which [`NoteArgs`] have been defined.
    pub fn get_note_args(&self) -> BTreeMap<NoteId, NoteArgs> {
        self.input_notes_args
            .iter()
            .filter_map(|(note, args)| args.map(|a| (*note, a)))
            .collect()
    }

    /// Returns the expected output own notes of the transaction.
    ///
    /// In this context "own notes" refers to notes that are expected to be created directly by the
    /// transaction script, rather than notes that are created as a result of consuming other notes.
    pub fn expected_output_own_notes(&self) -> Vec<Note> {
        match &self.script_template {
            Some(TransactionScriptTemplate::SendNotes(notes)) => notes
                .iter()
                .map(|partial| {
                    Note::with_attachments(
                        partial.assets().clone(),
                        *partial.partial_metadata(),
                        self.expected_output_recipients
                            .get(&partial.recipient_digest())
                            .expect("Recipient should be included if it's an own note")
                            .clone(),
                        partial.attachments().clone(),
                    )
                })
                .collect(),
            _ => vec![],
        }
    }

    /// Returns an iterator over the expected output notes.
    pub fn expected_output_recipients(&self) -> impl Iterator<Item = &NoteRecipient> {
        self.expected_output_recipients.values()
    }

    /// Returns an iterator over expected future notes.
    pub fn expected_future_notes(&self) -> impl Iterator<Item = &(NoteDetails, NoteTag)> {
        self.expected_future_notes.values()
    }

    /// Returns the [`TransactionScriptTemplate`].
    pub fn script_template(&self) -> &Option<TransactionScriptTemplate> {
        &self.script_template
    }

    /// Returns the [`AdviceMap`] for the transaction request.
    pub fn advice_map(&self) -> &AdviceMap {
        &self.advice_map
    }

    /// Returns a mutable reference to the [`AdviceMap`] for the transaction request.
    pub fn advice_map_mut(&mut self) -> &mut AdviceMap {
        &mut self.advice_map
    }

    /// Returns the [`MerkleStore`] for the transaction request.
    pub fn merkle_store(&self) -> &MerkleStore {
        &self.merkle_store
    }

    /// Returns the required foreign accounts keyed by account ID.
    pub fn foreign_accounts(&self) -> &BTreeMap<AccountId, ForeignAccount> {
        &self.foreign_accounts
    }

    /// Returns whether to ignore invalid input notes or not.
    pub fn ignore_invalid_input_notes(&self) -> bool {
        self.ignore_invalid_input_notes
    }

    /// Returns the script argument for the transaction request.
    pub fn script_arg(&self) -> &Option<Word> {
        &self.script_arg
    }

    /// Returns the auth argument for the transaction request.
    pub fn auth_arg(&self) -> &Option<Word> {
        &self.auth_arg
    }

    /// Returns the caller-declared salt for the native fee conversion info the client commits when
    /// preparing the transaction, set through [`TransactionRequestBuilder::fee_conversion_salt`].
    pub fn fee_conversion_salt(&self) -> Option<Word> {
        self.fee_conversion_salt
    }

    /// Returns whether the request carries an auth arg that commits anything.
    ///
    /// An empty word counts as no arg: otherwise it would suppress the conversion info the client
    /// attaches, leaving `fee::pay_fee` nothing to read.
    pub fn has_auth_arg(&self) -> bool {
        self.auth_arg.is_some_and(|auth_arg| auth_arg != Word::empty())
    }

    /// Returns the expected NTX scripts that the node's NTX builder will need in its registry.
    pub fn expected_ntx_scripts(&self) -> &[NoteScript] {
        &self.expected_ntx_scripts
    }

    // STATE MUTATORS
    // --------------------------------------------------------------------------------------------

    /// Adds `note` to the notes this request consumes, as an unauthenticated input.
    ///
    /// Building a request that consumes the note is the public way to do this. The harness needs it
    /// on a request a test already built.
    #[cfg(feature = "testing")]
    pub(crate) fn add_unauthenticated_input_note(&mut self, note: Note) {
        self.input_notes_args.push((note.id(), None));
        self.input_notes.push(note);
    }

    /// Commits fee conversion info paying the fee in `fee_faucet_id`'s asset at rate 1/1 under
    /// `salt`, through the auth args.
    pub(crate) fn commit_native_fee_conversion_info(
        &mut self,
        fee_faucet_id: AccountId,
        salt: Word,
    ) {
        let (auth_arg, preimage) =
            commit_fee_conversion_info(FeeConversionInfo::one_to_one(fee_faucet_id), salt);
        self.advice_map.insert(auth_arg, preimage);
        self.auth_arg = Some(auth_arg);
    }

    /// Checks the invariants every request must hold, whether it was built or deserialized.
    ///
    /// # Errors
    /// - If a note appears more than once among the input notes.
    fn validate(&self) -> Result<(), TransactionRequestError> {
        let mut seen_input_notes = BTreeSet::new();
        for (note_id, _) in &self.input_notes_args {
            if !seen_input_notes.insert(note_id) {
                return Err(TransactionRequestError::DuplicateInputNote(*note_id));
            }
        }

        Ok(())
    }

    /// Builds the [`InputNotes`] needed for the transaction execution.
    ///
    /// A note with a pinned mode keeps that mode. Any other note is authenticated when
    /// `authenticated_note_records` holds a record for it and unauthenticated otherwise. The result
    /// keeps the order of the request.
    pub(crate) fn build_input_notes(
        &self,
        authenticated_note_records: Vec<InputNoteRecord>,
    ) -> Result<InputNotes<InputNote>, TransactionRequestError> {
        let mut authenticated_notes: BTreeMap<NoteId, InputNoteRecord> = BTreeMap::new();
        for record in authenticated_note_records {
            // Authenticated note records always carry metadata (their inclusion proof injected it),
            // so `id()` is `Some`.
            let note_id =
                record.id().expect("authenticated note record carries metadata so id() is Some");

            if !record.is_authenticated() {
                return Err(TransactionRequestError::InputNoteNotAuthenticated(note_id));
            }
            if record.is_consumed() {
                return Err(TransactionRequestError::InputNoteAlreadyConsumed(
                    record.details_commitment(),
                ));
            }

            authenticated_notes.insert(note_id, record);
        }

        let input_notes = self
            .input_notes()
            .iter()
            .map(|note| match self.explicit_input_notes.get(&note.id()) {
                Some(input_note) => input_note.clone(),
                None => match authenticated_notes.remove(&note.id()) {
                    Some(record) => record
                        .try_into()
                        .expect("Authenticated note record should be convertible to InputNote"),
                    None => InputNote::unauthenticated(note.clone()),
                },
            })
            .collect();

        Ok(InputNotes::new(input_notes)?)
    }

    /// Converts the [`TransactionRequest`] into [`TransactionArgs`] in order to be executed by a
    /// Miden host.
    pub(crate) fn into_transaction_args(
        self,
        tx_script: Option<(TransactionScript, Option<Word>)>,
    ) -> TransactionArgs {
        let note_args = self.get_note_args();
        let TransactionRequest {
            expected_output_recipients,
            advice_map,
            merkle_store,
            ..
        } = self;

        let mut tx_args = TransactionArgs::new(advice_map).with_note_args(note_args);

        // A script argument without a script has nothing to bind to, so it is only applied when a
        // transaction script is present. With no argument the default empty word is used, which is
        // equivalent to setting no argument at all.
        if let Some((tx_script, script_args)) = tx_script {
            let script_args = script_args.or(self.script_arg).unwrap_or_default();
            tx_args = tx_args.with_tx_script_and_args(tx_script, script_args);
        }

        if let Some(auth_argument) = self.auth_arg {
            tx_args = tx_args.with_auth_args(auth_argument);
        }

        tx_args
            .extend_output_note_recipients(expected_output_recipients.into_values().map(Box::new));
        tx_args.extend_merkle_store(merkle_store.inner_nodes());

        tx_args
    }

    /// Builds the transaction script based on the account capabilities and the transaction request.
    ///
    /// Returns the script together with the `TX_SCRIPT_ARGS` word it must be executed with, if the
    /// script determines it. The `SendNotes` script reads the notes it creates from the advice
    /// provider and only receives their payload commitment on the stack, so its argument is fixed
    /// by the notes the script was built for, and passing anything else makes the script fail to
    /// resolve its payload. A caller-supplied [`TransactionScriptTemplate::CustomScript`] carries
    /// no such constraint and yields `None`, so the request's own
    /// [`TransactionRequestBuilder::script_arg`] applies to it.
    ///
    /// A request without a script template normally runs without a transaction script. When such a
    /// request sets an expiration delta, the standard [`ExpirationTransactionScript`] is used so
    /// that the delta is enforced; the script reads the delta from its own `TX_SCRIPT_ARGS`.
    ///
    /// Scripts supplied by the caller via [`TransactionScriptTemplate::CustomScript`] are expected
    /// to have already been compiled against the client's source manager (e.g. via
    /// [`Client::code_builder`](crate::Client::code_builder)).
    pub(crate) fn build_transaction_script(
        &self,
        code_interface: &AccountCodeInterface,
    ) -> Result<Option<(TransactionScript, Option<Word>)>, TransactionRequestError> {
        match &self.script_template {
            Some(TransactionScriptTemplate::CustomScript(script)) => {
                Ok(Some((script.clone(), None)))
            },
            Some(TransactionScriptTemplate::SendNotes(notes)) => {
                let script = match self.expiration_delta.and_then(NonZeroU16::new) {
                    Some(delta) => SendNotesTransactionScript::with_expiration_delta(
                        code_interface,
                        notes,
                        delta,
                    )?,
                    None => SendNotesTransactionScript::new(code_interface, notes)?,
                };
                Ok(Some((script.tx_script().clone(), Some(script.tx_script_args()))))
            },
            None => match self.expiration_delta.and_then(NonZeroU16::new) {
                Some(delta) => {
                    let script = ExpirationTransactionScript::new(delta);
                    Ok(Some((script.into(), Some(script.tx_script_args()))))
                },
                None => Ok(None),
            },
        }
    }
}

// SERIALIZATION
// ================================================================================================

impl Serializable for TransactionRequest {
    fn write_into<W: ByteWriter>(&self, target: &mut W) {
        self.input_notes.write_into(target);
        self.input_notes_args.write_into(target);
        self.explicit_input_notes.write_into(target);
        match &self.script_template {
            None => target.write_u8(0),
            Some(TransactionScriptTemplate::CustomScript(script)) => {
                target.write_u8(1);
                script.write_into(target);
            },
            Some(TransactionScriptTemplate::SendNotes(notes)) => {
                target.write_u8(2);
                notes.write_into(target);
            },
        }
        self.expected_output_recipients.write_into(target);
        self.expected_future_notes.write_into(target);
        self.advice_map.write_into(target);
        self.merkle_store.write_into(target);
        let foreign_accounts: Vec<_> = self.foreign_accounts.values().cloned().collect();
        foreign_accounts.write_into(target);
        self.expiration_delta.write_into(target);
        target.write_u8(u8::from(self.ignore_invalid_input_notes));
        self.script_arg.write_into(target);
        self.auth_arg.write_into(target);
        self.fee_conversion_salt.write_into(target);
        self.expected_ntx_scripts.write_into(target);
    }
}

impl Deserializable for TransactionRequest {
    fn read_from<R: ByteReader>(source: &mut R) -> Result<Self, DeserializationError> {
        let input_notes = Vec::<Note>::read_from(source)?;
        let input_notes_args = Vec::<(NoteId, Option<NoteArgs>)>::read_from(source)?;
        let explicit_input_notes = BTreeMap::<NoteId, InputNote>::read_from(source)?;
        for (note_id, input_note) in &explicit_input_notes {
            if *note_id != input_note.id() || !input_notes.contains(input_note.note()) {
                return Err(DeserializationError::InvalidValue(format!(
                    "explicit input note {note_id} does not match a request input note"
                )));
            }
        }

        let script_template = match source.read_u8()? {
            0 => None,
            1 => {
                let transaction_script = TransactionScript::read_from(source)?;
                Some(TransactionScriptTemplate::CustomScript(transaction_script))
            },
            2 => {
                let notes = Vec::<PartialNote>::read_from(source)?;
                Some(TransactionScriptTemplate::SendNotes(notes))
            },
            _ => {
                return Err(DeserializationError::InvalidValue(
                    "Invalid script template type".to_string(),
                ));
            },
        };

        let expected_output_recipients = BTreeMap::<Word, NoteRecipient>::read_from(source)?;
        let expected_future_notes =
            BTreeMap::<NoteDetailsCommitment, (NoteDetails, NoteTag)>::read_from(source)?;

        let advice_map = AdviceMap::read_from(source)?;
        let merkle_store = MerkleStore::read_from(source)?;
        let mut foreign_accounts = BTreeMap::new();
        for foreign_account in Vec::<ForeignAccount>::read_from(source)? {
            foreign_accounts.entry(foreign_account.account_id()).or_insert(foreign_account);
        }
        let expiration_delta = Option::<u16>::read_from(source)?;
        let ignore_invalid_input_notes = source.read_u8()? == 1;
        let script_arg = Option::<Word>::read_from(source)?;
        let auth_arg = Option::<Word>::read_from(source)?;
        let fee_conversion_salt = Option::<Word>::read_from(source)?;
        let expected_ntx_scripts = Vec::<NoteScript>::read_from(source)?;

        let request = TransactionRequest {
            input_notes,
            input_notes_args,
            explicit_input_notes,
            script_template,
            expected_output_recipients,
            expected_future_notes,
            advice_map,
            merkle_store,
            foreign_accounts,
            expiration_delta,
            ignore_invalid_input_notes,
            script_arg,
            auth_arg,
            fee_conversion_salt,
            expected_ntx_scripts,
        };
        request
            .validate()
            .map_err(|err| DeserializationError::InvalidValue(err.to_string()))?;

        Ok(request)
    }
}

// HELPERS
// ================================================================================================

/// Accumulates fungible totals and collectable non-fungible assets from an iterator of assets.
///
/// An asset that is neither fungible nor non-fungible is left out of both buckets, since neither
/// balance arithmetic applies to it. Execution judges such an asset instead.
pub(crate) fn collect_assets<'a>(
    assets: impl Iterator<Item = &'a Asset>,
) -> (BTreeMap<AccountId, u64>, Vec<Asset>) {
    let mut fungible_balance_map = BTreeMap::new();
    let mut non_fungible_set = Vec::new();

    for asset in assets {
        if let Some(fungible) = asset.as_fungible() {
            let amount = fungible.amount().as_u64();
            fungible_balance_map
                .entry(fungible.faucet_id())
                .and_modify(|balance| *balance += amount)
                .or_insert(amount);
        } else if asset.is_non_fungible() && !non_fungible_set.contains(asset) {
            non_fungible_set.push(*asset);
        }
    }

    (fungible_balance_map, non_fungible_set)
}

impl Default for TransactionRequestBuilder {
    fn default() -> Self {
        Self::new()
    }
}

// TRANSACTION REQUEST ERROR
// ================================================================================================

// Errors related to a [TransactionRequest]
#[derive(Debug, Error)]
pub enum TransactionRequestError {
    #[error("failed to build the send-notes transaction script")]
    SendNotesTransactionScriptError(#[from] SendNotesTransactionScriptError),
    #[error("account error")]
    AccountError(#[from] AccountError),
    #[error("asset error")]
    AssetError(#[from] AssetError),
    #[error("duplicate input note: note {0} was added more than once to the transaction")]
    DuplicateInputNote(NoteId),
    #[error("transaction expiration delta must be greater than zero")]
    ZeroExpirationDelta,
    #[error(
        "the account proof does not contain the required foreign account data; re-fetch the proof and retry"
    )]
    ForeignAccountDataMissing,
    #[error(
        "foreign account {0} has incompatible visibility; use `ForeignAccount::public()` for public accounts and `ForeignAccount::private()` for private accounts"
    )]
    InvalidForeignAccountId(AccountId),
    #[error(
        "note {0} cannot be used as an authenticated input: it does not have a valid inclusion proof"
    )]
    InputNoteNotAuthenticated(NoteId),
    #[error("note with details commitment {} has already been consumed", .0.to_hex())]
    InputNoteAlreadyConsumed(NoteDetailsCommitment),
    #[error(
        "note with details commitment {} is being consumed by pending transaction {transaction_id}",
        note.to_hex()
    )]
    InputNoteBeingProcessed {
        note: NoteDetailsCommitment,
        transaction_id: TransactionId,
    },
    #[error(
        "output note declares sender {actual} but the transaction is executed by account {expected}"
    )]
    OutputNoteSenderMismatch { expected: AccountId, actual: AccountId },
    #[error(
        "the request declares a fee conversion salt but the account's auth component {0} does not \
         read the auth args as fee conversion info"
    )]
    FeeConversionInfoUnsupported(String),
    #[error(
        "account's `{0}` component reuses the fee conversion salt as a replay guard, so the \
         caller must declare a fresh one with `TransactionRequestBuilder::fee_conversion_salt`"
    )]
    FeeConversionInfoRequired(String),
    #[error("invalid transaction script")]
    InvalidTransactionScript(#[from] MastForestScriptError),
    #[error("merkle proof error")]
    MerkleError(#[from] MerkleError),
    #[error("empty transaction: the request has no input notes and no account state changes")]
    NoInputNotesNorAccountChange,
    #[error("note not found: {0}")]
    NoteNotFound(String),
    #[error("failed to create note")]
    NoteCreationError(#[from] NoteError),
    #[error("note failed validation")]
    NoteValidationError(#[source] NoteError),
    #[error("note execution failed")]
    NoteExecutionError(#[source] NoteError),
    #[error("failed to build note args")]
    NoteArgError(#[source] NoteError),
    #[error("pay-to-ID note must contain at least one asset to transfer")]
    P2IDNoteWithoutAsset,
    #[error("swap note assets must be non-zero: a zero {0} asset makes the exchange one-sided")]
    SwapNoteWithZeroAsset(&'static str),
    #[error(
        "non-fungible asset issued by faucet {0} is not available in the account vault or incoming notes"
    )]
    MissingNonFungibleAsset(AccountId),
    #[error("PSWAP note can only be cancelled by its creator: expected {expected}, got {actual}")]
    PswapCancelCreatorMismatch { expected: AccountId, actual: AccountId },
    #[error("error building script")]
    CodeBuilderError(#[from] CodeBuilderError),
    #[error("transaction script template error: {0}")]
    ScriptTemplateError(String),
    #[error("foreign procedure takes at most {max} input felts, got {actual}")]
    ForeignProcedureInputsTooLong { max: usize, actual: usize },
    #[error("storage slot {0} not found in account ID {1}")]
    StorageSlotNotFound(u8, AccountId),
    #[error("error while building the input notes")]
    TransactionInputError(#[from] TransactionInputError),
    #[error("account storage map error")]
    StorageMapError(#[from] StorageMapError),
    #[error("asset vault error")]
    AssetVaultError(#[from] AssetVaultError),
    #[error(
        "unsupported authentication scheme ID {0}; supported schemes are: RpoFalcon512 (0) and EcdsaK256Keccak (1)"
    )]
    UnsupportedAuthSchemeId(u8),
}

// TESTS
// ================================================================================================

#[cfg(test)]
mod tests {
    use std::vec::Vec;

    use miden_protocol::account::auth::{AuthScheme, PublicKeyCommitment};
    use miden_protocol::account::{
        AccountBuilder,
        AccountComponent,
        AccountId,
        AccountType,
        StorageMapKey,
        StorageSlotName,
    };
    use miden_protocol::asset::FungibleAsset;
    use miden_protocol::crypto::rand::{FeltRng, RandomCoin};
    use miden_protocol::note::{NoteTag, NoteType};
    use miden_protocol::testing::account_id::{
        ACCOUNT_ID_PRIVATE_FUNGIBLE_FAUCET,
        ACCOUNT_ID_REGULAR_PUBLIC_ACCOUNT_IMMUTABLE_CODE,
        ACCOUNT_ID_SENDER,
    };
    use miden_protocol::transaction::InputNote;
    use miden_protocol::{EMPTY_WORD, Felt, Word};
    use miden_standards::account::auth::{Approver, AuthSingleSig};
    use miden_standards::note::P2idNote;
    use miden_standards::testing::account_component::MockAccountComponent;
    use miden_tx::utils::serde::{Deserializable, Serializable};

    use super::{
        ExpirationTransactionScript,
        NonZeroU16,
        TransactionRequest,
        TransactionRequestBuilder,
        TransactionScript,
    };
    use crate::rpc::domain::account::AccountStorageRequirements;
    use crate::transaction::ForeignAccount;

    #[test]
    fn transaction_request_serialization() {
        assert_transaction_request_serialization_with(|| {
            AuthSingleSig::new(Approver::new(
                PublicKeyCommitment::from(EMPTY_WORD),
                AuthScheme::Falcon512Poseidon2,
            ))
            .into()
        });
    }

    #[test]
    fn transaction_request_serialization_ecdsa() {
        assert_transaction_request_serialization_with(|| {
            AuthSingleSig::new(Approver::new(
                PublicKeyCommitment::from(EMPTY_WORD),
                AuthScheme::EcdsaK256Keccak,
            ))
            .into()
        });
    }

    #[test]
    fn expiration_delta_without_script_template_builds_expiration_script() {
        let account = AccountBuilder::new(Default::default())
            .with_component(MockAccountComponent::with_empty_slots())
            .with_component(AuthSingleSig::new(Approver::new(
                PublicKeyCommitment::from(EMPTY_WORD),
                AuthScheme::Falcon512Poseidon2,
            )))
            .account_type(AccountType::Private)
            .build_existing()
            .unwrap();
        let code_interface = account.code_interface();

        let delta = NonZeroU16::new(9).unwrap();
        let tx_request =
            TransactionRequestBuilder::new().expiration_delta(delta.get()).build().unwrap();

        let (script, script_args) =
            tx_request.build_transaction_script(&code_interface).unwrap().unwrap();
        let expected = ExpirationTransactionScript::new(delta);
        assert_eq!(script.root(), TransactionScript::from(expected).root());
        assert_eq!(script_args, Some(expected.tx_script_args()));

        // Without a delta there is still no script to run.
        let tx_request = TransactionRequestBuilder::new().build().unwrap();
        assert!(tx_request.build_transaction_script(&code_interface).unwrap().is_none());
    }

    #[test]
    fn deserialization_rejects_duplicate_input_notes() {
        let sender_id = AccountId::try_from(ACCOUNT_ID_SENDER).unwrap();
        let target_id =
            AccountId::try_from(ACCOUNT_ID_REGULAR_PUBLIC_ACCOUNT_IMMUTABLE_CODE).unwrap();
        let faucet_id = AccountId::try_from(ACCOUNT_ID_PRIVATE_FUNGIBLE_FAUCET).unwrap();
        let note = P2idNote::builder()
            .sender(sender_id)
            .target(target_id)
            .assets(vec![FungibleAsset::new(faucet_id, 100).unwrap()])
            .note_type(NoteType::Private)
            .generate_serial_number(&mut RandomCoin::new(Word::default()))
            .build()
            .unwrap();

        // The builder rejects a duplicate, so the built request is corrupted by hand.
        let mut tx_request = TransactionRequestBuilder::new()
            .input_notes(vec![(note.into(), None)])
            .build()
            .unwrap();
        let note_id = tx_request.input_note_ids().next().unwrap();
        tx_request.input_notes.push(tx_request.input_notes[0].clone());
        tx_request.input_notes_args.push((note_id, None));

        assert!(TransactionRequest::read_from_bytes(&tx_request.to_bytes()).is_err());
    }

    fn assert_transaction_request_serialization_with<F>(auth_component: F)
    where
        F: FnOnce() -> AccountComponent,
    {
        let sender_id = AccountId::try_from(ACCOUNT_ID_SENDER).unwrap();
        let target_id =
            AccountId::try_from(ACCOUNT_ID_REGULAR_PUBLIC_ACCOUNT_IMMUTABLE_CODE).unwrap();
        let faucet_id = AccountId::try_from(ACCOUNT_ID_PRIVATE_FUNGIBLE_FAUCET).unwrap();
        let mut rng = RandomCoin::new(Word::default());

        let mut notes = vec![];
        for i in 0..7 {
            let note = P2idNote::builder()
                .sender(sender_id)
                .target(target_id)
                .assets(vec![FungibleAsset::new(faucet_id, 100 + i).unwrap()])
                .note_type(NoteType::Private)
                .generate_serial_number(&mut rng)
                .build()
                .expect("note creation failed");
            notes.push(note.into());
        }

        let mut advice_vec: Vec<(Word, Vec<Felt>)> = vec![];
        for i in 0u32..10 {
            advice_vec.push((rng.draw_word(), vec![Felt::from(i)]));
        }

        let account = AccountBuilder::new(Default::default())
            .with_component(MockAccountComponent::with_empty_slots())
            .with_component(auth_component())
            .account_type(AccountType::Private)
            .build_existing()
            .unwrap();

        // This transaction request wouldn't be valid in a real scenario, it's intended for testing
        let tx_request = TransactionRequestBuilder::new()
            .input_notes(vec![(notes.pop().unwrap(), None)])
            .explicit_input_notes(vec![(
                InputNote::unauthenticated(notes.pop().unwrap()),
                Some(rng.draw_word()),
            )])
            .expected_output_recipients(vec![notes.pop().unwrap().recipient().clone()])
            .expected_future_notes(vec![(
                notes.pop().unwrap().into(),
                NoteTag::with_account_target(sender_id),
            )])
            .extend_advice_map(advice_vec)
            .foreign_accounts([
                ForeignAccount::public(
                    target_id,
                    AccountStorageRequirements::new([(
                        StorageSlotName::new("demo::storage_slot").unwrap(),
                        &[StorageMapKey::new(Word::default())],
                    )]),
                )
                .unwrap(),
                ForeignAccount::private(&account).unwrap(),
            ])
            .own_output_notes(vec![notes.pop().unwrap(), notes.pop().unwrap()])
            .script_arg(rng.draw_word())
            .auth_arg(rng.draw_word())
            .expected_ntx_scripts(vec![notes.first().unwrap().recipient().script().clone()])
            .build()
            .unwrap();

        let mut buffer = Vec::new();
        tx_request.write_into(&mut buffer);

        let deserialized_tx_request = TransactionRequest::read_from_bytes(&buffer).unwrap();
        assert_eq!(tx_request, deserialized_tx_request);
    }
}
